spring:
  profiles:
    default: local
  config:
    import:
      - classpath:/application-domain.yml

witheang:
  auth:
    jwt-secret-key: ENC(i5HqamjyyaTwDSyiHXoAxJrP11XyQ8mArvAUI1RD15tteCbIEnzVVp+qcYB45xDkybBZmjY79HDp/Ci5YkkSyg==)